[[entries]]
title = "info"
entries = [
   { title = "I'm a PhD student at <a href='https://www.lix.polytechnique.fr/'>LIX</a> working on formal methods for mobile robotics" },
   { title = "You can find here my <a href='https://github.com/birromer/'>github</a>, <a href='https://orcid.org/0000-0003-2325-1497'>orcid</a> and <a href='https://www.linkedin.com/in/bernardo-h-57239312a/'>linkedin</a>" },
  ]

# [[entries]]
# title = "[ <a href='posts'>posts</a> | <a href='tags'>tags</a> ]"

[[entries]]
title = "posts"
url = "posts"

[[entries]]
title = "tags"
url = "tags"

[[entries]]
title = "recent"

  [entries.post_list]
  limit = 5
  show_more = true
  show_more_text = "rest of the stuff ..."
  show_more_url = "posts"
